### ISSUE TITLE
[decancer] Remove [p]dc alias

### ISSUE THREAD

**Issue by DariusStClair** [kablekompany/Kable-Kogs#31]
**Is your feature request related to a problem? Please describe.**
Imma use the template: I'm always frustrated when I try to disconnect audio player with [p]dc used as an alias for [p]disconnect but instead decancer pops up, same as the majority of my users.

**Describe the solution you'd like**
Please remove the [alias for decancer command](https://github.com/kablekompany/Kable-Kogs/blob/0edd03c8b7fba8744d1aa4c226b4ce04c9015860/decancer/decancer.py#L248).

**Describe alternatives you've considered**
People should be able to pick what they want to alias.

Thanks!

**Comment by kablekompany** [comment]
Removed. Update and should be good when discord is done shitting.
