### ISSUE TITLE
[LockItUp] Resync a channel that was previously synced.

### ISSUE THREAD

**Issue by madebylydia** [kablekompany/Kable-Kogs#33]
**Describe the bug**

**To Reproduce**
1. Install "lockitup" (wow)
2. Load it (wow²)
3; Run "[p]lockit" with a channel that has permissions synced with a category.
4. Run "[p]unlockit" with the same channel.

**Expected behavior**
The bot sync the permissions again.

**Actual behavior**
The bot does not sync the permissions.

**Desktop (please complete the following information):**
Unrelated.

**Smartphone (please complete the following information):**
Are you... why?

**Additional context**
"Please insert your phone operator's name here and your security number"

**Comment by kablekompany** [comment]
Currently it's hard wired perms (@@everyone neutral for unlock, or @@everyone negative for lock)

Should be easy enough to cache the perms state on lock to return them to that state on unlock, however persistently I'm unsure (if bot restarts while channel is locked)

I'll give it some thought on approach for implementing

**Comment by madebylydia** [comment]
I haven't look at the code, but is everyone just getting removed permission to write when locking? And getting reset when unlocking?

**Comment by phenom4n4n** [comment]
That is the current implementation, however I support the idea of checking if the channel is synced previously and resyncing rather than unlocking.
